name: Cache Remote Rando Files

on:
  push:
    branches: [ tracker_integration ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          ssh-keyscan -p SSH_PORT -H $SSH_HOST >> ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_PORT: ${{secrets.SSH_PORT}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: Login and download remote files
        run: ssh -i $SSH_KEY_PATH -p $SSH_PORT $SSH_USER@$SSH_HOST "rm -rf ~/randomizer-graph-tool && git clone https://github.com/mracsys/randomizer-graph-tool.git && cd ~/randomizer-graph-tool && pnpm install --frozen-lockfile && pnpm run downloadRandos"
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_PORT: ${{secrets.SSH_PORT}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key